const products = [
  {
    id: 1,
    name: "Jordan Air 16 Low",
    price: "$30.99",
    availability: <p className=" text-orange-500 ">only 16 remaining</p>,
    image:
      "https://images.pexels.com/photos/10134303/pexels-photo-10134303.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    percentage: "10% off",
    percentageOff: <p>10.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500 max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star-half text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 2,
    name: "Nike Awesome Air",
    price: "$50.99",
    availability: <p className=" text-orange-500 ">Almost sold out</p>,
    image:
      "https://images.pexels.com/photos/8979069/pexels-photo-8979069.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    percentage: "20% off",
    percentageOff: <p>29.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 3,
    name: "Nike React Air 87",
    price: "$30.99",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=600",
    percentage: "10% off",
    percentageOff: <p>10.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: "$20.99",
    availability: <p className=" text-orange-500 ">Almost sold out</p>,
    image:
      "https://images.pexels.com/photos/17918935/pexels-photo-17918935/free-photo-of-shoes-close-up.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",

    percentage: "45% off",
    percentageOff: <p>45.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 5,
    name: "Puma Suede Classic",
    price: "$35.99",
    availability: <p className=" text-orange-500 ">Only 4 remaining</p>,
    image:
      "https://images.pexels.com/photos/12879626/pexels-photo-12879626.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    percentage: "60% off",
    percentageOff: <p>60.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star-half text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 6,
    name: "White & Black Polo",
    price: "$50.00",
    availability: <p className=" text-orange-500 ">Almost sold out</p>,
    image:
      "https://images.pexels.com/photos/18186105/pexels-photo-18186105/free-photo-of-basic-black-and-white-t-shirts.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    percentage: "50% off",
    percentageOff: <p>50.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star-half text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 7,
    name: "3 Pairs of Jeans ",
    price: "$80.99",
    availability: <p className=" text-orange-500 ">Only 20 remaining</p>,
    image:
      "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    percentage: "10% off",
    percentageOff: <p>10.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star-half text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 8,
    name: "Female Crop Top",
    price: "$35.00",
    availability: <p className=" text-orange-500 ">Sold out</p>,
    image:
      "https://i.pinimg.com/236x/a6/f5/18/a6f51874b7e74186395759aace28c44a.jpg",

    percentage: "5% off",
    percentageOff: <p>5.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 9,
    name: " Long Hoodie",
    price: "$80.99",
    availability: <p className=" text-orange-500 ">Only 5 remaining</p>,
    image:
      "https://i.pinimg.com/736x/ce/72/ad/ce72ade952f54326361f14284d493d9f.jpg",
    percentage: "20% off",
    percentageOff: <p>20.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 10,
    name: "Face Cap",
    price: "$40.00",
    availability: <p className=" text-orange-500 ">Sold out</p>,
    image:
      "https://images.pexels.com/photos/9558758/pexels-photo-9558758.jpeg?auto=compress&cs=tinysrgb&w=600",
    percentage: "5% off",
    percentageOff: <p>5.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 11,
    name: "300 watts Blender Machine",
    price: "$100.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://images.pexels.com/photos/1797103/pexels-photo-1797103.jpeg?auto=compress&cs=tinysrgb&w=600",
    percentage: "5% off",
    percentageOff: <p>5.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 12,
    name: "Black Female Gown",
    price: "$30.00",
    availability: <p className=" text-orange-500 ">Only 10 remaining</p>,
    image:
      "https://i.pinimg.com/736x/fd/35/27/fd3527a97e92d2cf8c7f4dc8291c28cb.jpg",
    percentage: "10% off",
    percentageOff: <p>10.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 13,
    name: "Men trackers",
    price: "$100.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/474x/95/1d/00/951d000caf826eb9329ee88d414080a0.jpg",
    percentage: "5% off",
    percentageOff: <p>5.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 14,
    name: "Unisex Footwear",
    price: "$55.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/736x/39/a4/cd/39a4cdb69beb49514dbfd26908935464.jpg",
    percentage: "15% off",
    percentageOff: <p>15.00</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star-half text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 15,
    name: "Quality Bikers Polo",
    price: "$100.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/736x/8c/cd/c9/8ccdc91d6c1830e95ddeafc8b086dea2.jpg",
    percentage: "5% off",
    percentageOff: <p>5.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 16,
    name: "JBL Max 100",
    price: "$60.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/736x/1a/11/02/1a1102b3237a99cc31b40d6c88c67cc6.jpg",
    percentage: "10% off",
    percentageOff: <p>10.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 17,
    name: "AirPods Pro 10",
    price: "$10.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      " https://i.pinimg.com/236x/16/33/44/163344a296be2887f176612bde602d30.jpg",
    percentage: "20% off",
    percentageOff: <p>20.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 18,
    name: "Ultra Light weight unisex slippers",
    price: "$70.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/736x/4f/60/21/4f60210e1418923f3fadc3291a4874a0.jpg",
    percentage: "30% off",
    percentageOff: <p>30.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 19,
    name: "Aesthetic Women Slippers",
    price: "$40.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/236x/bf/a1/36/bfa136c5feea76490de6a8ddcbf2ff01.jpg",
    percentage: "10% off",
    percentageOff: <p>10.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
  {
    id: 20,
    name: "Echo 360",
    price: "$100.00",
    availability: <p className=" text-orange-500 ">Still in stock</p>,
    image:
      "https://i.pinimg.com/236x/0a/03/4d/0a034dd6025c9536ce9f8a74c8f46fa3.jpg",
    percentage: "5% off",
    percentageOff: <p>5.99</p>,
    rating: [
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bxs-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
      <i class="bx bx-star text-yellow-500  max-md:text-[19px] text-[23px]"></i>,
    ],
  },
];
